### ISSUE TITLE
Examples don't compile (TH fails)

### ISSUE THREAD

**Issue by oliver-batchelor** [pa-ba/compdata-param#7]
examples/Multi/Lambda.hs fails to compile with ghc 8.0, the Template Haskell generates some invalid code?

GHC 8.0.1, hackage 0.9.1 version.

$(derive [smartConstructors, makeHDifunctor, makeEqHD, makeShowHD]
         [''Lam, ''App, ''Const, ''Plus, ''Err])

src/Lambda.hs:43:3: error:
    • Couldn't match type ‘K’
                     with ‘f0 Data.Comp.Param.Multi.FreshM.Name’
      Expected type: f0 Data.Comp.Param.Multi.FreshM.Name (K (Data.Comp.Param.Multi.FreshM.FreshM
                                                                String)) Int
        Actual type: K (Data.Comp.Param.Multi.FreshM.FreshM String) Int
    • In the first argument of ‘showHD’, namely ‘x_a93R’
      In the expression: showHD x_a93R
      In the first argument of ‘sequence’, namely
        ‘[showHD x_a93R, showHD x_a93S]’

src/Lambda.hs:43:3: error:
    • Couldn't match expected type ‘t0 (K (Data.Comp.Param.Multi.FreshM.FreshM
                                             String)
                                          i0)’
                  with actual type ‘Int’
    • In the second argument of ‘mapM’, namely ‘x_a93P’
      In the second argument of ‘($)’, namely
        ‘(mapM
            ((GHC.Base.liftM
                compdata-param-0.9.1:Data.Comp.Param.Multi.Derive.Show.Dummy)
             . unK)
            x_a93P)’
      In the expression:
        ((GHC.Base.liftM show)
         $ (mapM
              ((GHC.Base.liftM
                  compdata-param-0.9.1:Data.Comp.Param.Multi.Derive.Show.Dummy)
               . unK)
              x_a93P))

src/Lambda.hs:43:3: error:
    • Couldn't match type ‘Data.Comp.Param.Multi.FreshM.Name i1’
                     with ‘K (Data.Comp.Param.Multi.FreshM.FreshM String)’
      Expected type: f2 Data.Comp.Param.Multi.FreshM.Name (K (Data.Comp.Param.Multi.FreshM.FreshM
                                                                String)) (K (Data.Comp.Param.Multi.FreshM.FreshM
                                                                               String)
                                                                            j)
        Actual type: Data.Comp.Param.Multi.FreshM.Name i1
                     -> K (Data.Comp.Param.Multi.FreshM.FreshM String) j
    • In the first argument of ‘showHD’, namely ‘x_a93K’
      In the expression: showHD x_a93K
      In the first argument of ‘sequence’, namely ‘[showHD x_a93K]’
    • Relevant bindings include
        x_a93K :: Data.Comp.Param.Multi.FreshM.Name i1
                  -> K (Data.Comp.Param.Multi.FreshM.FreshM String) j
          (bound at src/Lambda.hs:43:3)

**Comment by oliver-batchelor** [comment]
The problem is this part:

```
      | not (containsType tp conArg) &&
              not (containsType tp coArg) =
                [| return $ show $(varE x) |]
```

Specifically the second clause 

```
    not (containsType tp coArg)
```

Since the argument is a simple 'Int' I'm asuming 'show' is the correct function call.

```
data Const :: (Type -> Type) -> (Type -> Type) -> (Type -> Type) where
  Const :: Int -> Const a b Int
```

**Comment by oliver-batchelor** [comment]
So in this instance coArg = ConT GHC.Types.Int  and tp = ConT GHC.Types.Int ... which is equal, so is this conditional wrong?

**Comment by oliver-batchelor** [comment]
Seems to work without that check. However makeShowHD  for Plus also fails in a different way.
